In [28]:
import pandas as pd
import numpy as np
%matplotlib inline
import os
import matplotlib.pyplot as plt
import calplot
from pandas.api.types import CategoricalDtype
import seaborn as sns
from scipy import stats
from bokeh.models import FactorRange,ColumnDataSource, Dropdown
from bokeh.plotting import figure
from bokeh.io import output_file, show

In [2]:
df = pd.read_csv('Police_Department_Incident_Reports__Historical_2003_to_May_2018.csv')
focuscrimes = ['WEAPON LAWS', 'PROSTITUTION', 'DRIVING UNDER THE INFLUENCE', 'ROBBERY', 'BURGLARY', 'ASSAULT', 'DRUNKENNESS', 'DRUG/NARCOTIC', 'TRESPASS', 'LARCENY/THEFT', 'VANDALISM', 'VEHICLE THEFT', 'STOLEN PROPERTY', 'DISORDERLY CONDUCT']

In [3]:
df.columns

Index(['PdId', 'IncidntNum', 'Incident Code', 'Category', 'Descript',
       'DayOfWeek', 'Date', 'Time', 'PdDistrict', 'Resolution', 'Address', 'X',
       'Y', 'location', 'SF Find Neighborhoods 2 2',
       'Current Police Districts 2 2', 'Current Supervisor Districts 2 2',
       'Analysis Neighborhoods 2 2', 'DELETE - Fire Prevention Districts 2 2',
       'DELETE - Police Districts 2 2', 'DELETE - Supervisor Districts 2 2',
       'DELETE - Zip Codes 2 2', 'DELETE - Neighborhoods 2 2',
       'DELETE - 2017 Fix It Zones 2 2',
       'Civic Center Harm Reduction Project Boundary 2 2',
       'Fix It Zones as of 2017-11-06  2 2', 'DELETE - HSOC Zones 2 2',
       'Fix It Zones as of 2018-02-07 2 2',
       'CBD, BID and GBD Boundaries as of 2017 2 2',
       'Areas of Vulnerability, 2016 2 2',
       'Central Market/Tenderloin Boundary 2 2',
       'Central Market/Tenderloin Boundary Polygon - Updated 2 2',
       'HSOC Zones as of 2018-06-05 2 2', 'OWED Public Spaces 2 2',
       'Neighborhoods 2'],
      dtype='object')

In [4]:
df['Date'] = pd.to_datetime(df['Date'])
df['Time'] = pd.to_datetime(df['Time'])
df['Month']=df['Date'].dt.month

In [5]:

df['Year'] =df['Date'].dt.strftime('%Y')

,PdId,IncidntNum,Incident Code,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,...,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2,Month,Year
0,4133422003074,41334220,3074,ROBBERY,"ROBBERY, BODILY FORCE",Monday,2004-11-22,2023-03-27 17:50:00,INGLESIDE,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,2004
1,5118535807021,51185358,7021,VEHICLE THEFT,STOLEN AUTOMOBILE,Tuesday,2005-10-18,2023-03-27 20:00:00,PARK,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2005
2,4018830907021,40188309,7021,VEHICLE THEFT,STOLEN AUTOMOBILE,Sunday,2004-02-15,2023-03-27 02:00:00,SOUTHERN,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2004
3,11014543126030,110145431,26030,ARSON,ARSON,Friday,2011-02-18,2023-03-27 05:27:00,INGLESIDE,NONE,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,94.0,2,2011
4,10108108004134,101081080,4134,ASSAULT,BATTERY,Sunday,2010-11-21,2023-03-27 17:00:00,SOUTHERN,NONE,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,32.0,11,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129520,17050730416710,170507304,16710,DRUG/NARCOTIC,POSSESSION OF NARCOTICS PARAPHERNALIA,Thursday,2017-06-22,2023-03-27 01:42:00,CENTRAL,"ARREST, CITED",...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,77.0,6,2017
2129521,17071435504014,170714355,4014,ASSAULT,AGGRAVATED ASSAULT WITH BODILY FORCE,Friday,2017-09-01,2023-03-27 17:00:00,PARK,NONE,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,112.0,9,2017
2129522,17053348465010,170533484,65010,OTHER OFFENSES,TRAFFIC VIOLATION ARREST,Friday,2017-06-30,2023-03-27 17:50:00,BAYVIEW,"ARREST, BOOKED",...,22.0,NaN,1.0,NaN,NaN,NaN,NaN,56.0,6,2017
2129523,17102776330130,171027763,30130,OTHER OFFENSES,PEDDLING WITHOUT A LICENSE,Wednesday,2017-12-20,2023-03-27 15:41:00,SOUTHERN,"ARREST, BOOKED",...,3.0,7.0,2.0,1.0,1.0,1.0,35.0,21.0,12,2017
2129524,17088142128160,170881421,28160,VANDALISM,"MALICIOUS MISCHIEF, VANDALISM OF VEHICLES",Friday,2017-10-27,2023-03-27 21:30:00,INGLESIDE,NONE,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,66.0,10,2017

In [7]:
df[(df['Date']>='2010')&(df['Date']<='2018')]['Date']
df = df[(df['Year']>='2008')&(df['Year']<='2018')]

In [8]:
df = df[df['Category']=='DRUG/NARCOTIC']

,PdId,IncidntNum,Incident Code,Category,Descript,DayOfWeek,Date,Time,PdDistrict,Resolution,...,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2,Month,Year
200,12091946416010,120919464,16010,DRUG/NARCOTIC,POSSESSION OF MARIJUANA,Tuesday,2012-11-13,2023-03-27 13:25:00,NORTHERN,"ARREST, BOOKED",...,NaN,8.0,2.0,1.0,1.0,1.0,NaN,21.0,11,2012
223,10087835716110,100878357,16110,DRUG/NARCOTIC,POSSESSION OF HEROIN FOR SALES,Wednesday,2010-09-22,2023-03-27 01:15:00,TENDERLOIN,NONE,...,18.0,6.0,2.0,1.0,1.0,1.0,NaN,20.0,9,2010
240,10039096916623,100390969,16623,DRUG/NARCOTIC,POSSESSION OF BASE/ROCK COCAINE FOR SALE,Wednesday,2010-04-28,2023-03-27 07:20:00,PARK,"ARREST, BOOKED",...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,12.0,4,2010
265,12009535916664,120095359,16664,DRUG/NARCOTIC,SALE OF CONTROLLED SUBSTANCE,Friday,2012-02-03,2023-03-27 16:27:00,TENDERLOIN,"ARREST, BOOKED",...,18.0,6.0,2.0,1.0,1.0,NaN,NaN,20.0,2,2012
269,8080506816110,80805068,16110,DRUG/NARCOTIC,POSSESSION OF HEROIN FOR SALES,Thursday,2008-07-31,2023-03-27 12:11:00,TENDERLOIN,"ARREST, BOOKED",...,18.0,6.0,2.0,1.0,1.0,1.0,NaN,20.0,7,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2129328,17084842116704,170848421,16704,DRUG/NARCOTIC,LOITERING WHERE NARCOTICS ARE SOLD/USED,Tuesday,2017-10-17,2023-03-27 02:00:00,NORTHERN,"ARREST, BOOKED",...,NaN,NaN,2.0,1.0,1.0,NaN,NaN,20.0,10,2017
2129398,17098433216030,170984332,16030,DRUG/NARCOTIC,POSSESSION OF MARIJUANA FOR SALES,Tuesday,2017-12-05,2023-03-27 11:23:00,NORTHERN,"ARREST, BOOKED",...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,15.0,12,2017
2129476,17087629016710,170876290,16710,DRUG/NARCOTIC,POSSESSION OF NARCOTICS PARAPHERNALIA,Thursday,2017-10-26,2023-03-27 16:24:00,SOUTHERN,"ARREST, BOOKED",...,NaN,5.0,2.0,NaN,NaN,NaN,35.0,19.0,10,2017
2129517,16026805516710,160268055,16710,DRUG/NARCOTIC,POSSESSION OF NARCOTICS PARAPHERNALIA,Friday,2016-04-01,2023-03-27 10:36:00,NORTHERN,"ARREST, BOOKED",...,NaN,10.0,2.0,NaN,NaN,NaN,NaN,50.0,4,2016
2129520,17050730416710,170507304,16710,DRUG/NARCOTIC,POSSESSION OF NARCOTICS PARAPHERNALIA,Thursday,2017-06-22,2023-03-27 01:42:00,CENTRAL,"ARREST, CITED",...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,77.0,6,2017

In [10]:
DayHour_Category = pd.DataFrame(df.groupby(['Year','Month']).count()['PdId']).reset_index()

     Year  Month  PdId
0    2008      1   972
1    2008      2  1050
2    2008      3  1069
3    2008      4   811
4    2008      5   904
..    ...    ...   ...
120  2018      1   330
121  2018      2   316
122  2018      3   368
123  2018      4   305
124  2018      5   150

[125 rows x 3 columns]

In [11]:
DayHour_Category = DayHour_Category.pivot(index='Month', columns='Year', values='PdId')

Year,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
Month,,,,,,,,,,,
1,972.0,1040.0,871.0,734.0,599.0,602.0,563.0,402.0,359.0,326.0,330.0
2,1050.0,909.0,760.0,707.0,559.0,573.0,541.0,306.0,372.0,261.0,316.0
3,1069.0,1242.0,961.0,592.0,654.0,628.0,531.0,399.0,397.0,315.0,368.0
4,811.0,1089.0,683.0,552.0,510.0,582.0,487.0,306.0,422.0,324.0,305.0
5,904.0,943.0,853.0,565.0,559.0,616.0,480.0,296.0,388.0,317.0,150.0
6,784.0,801.0,778.0,627.0,466.0,523.0,409.0,296.0,327.0,197.0,NaN
7,1064.0,803.0,682.0,527.0,459.0,571.0,467.0,293.0,261.0,240.0,NaN
8,911.0,1226.0,763.0,498.0,514.0,557.0,459.0,375.0,362.0,269.0,NaN
9,918.0,1137.0,744.0,606.0,480.0,548.0,468.0,368.0,294.0,225.0,NaN
10,1095.0,917.0,746.0,481.0,522.0,570.0,366.0,392.0,395.0,251.0,NaN
11,1026.0,901.0,572.0,485.0,505.0,486.0,320.0,456.0,319.0,239.0,NaN
12,852.0,763.0,623.0,428.0,480.0,416.0,233.0,305.0,306.0,301.0,NaN

In [12]:

DayHour_Category = DayHour_Category.drop('2018', axis=1)

In [13]:
#DayHour_Category = DayHour_Category / DayHour_Category.max()

DayHour_Category  = DayHour_Category .div(DayHour_Category .max().max())

In [14]:
DayHour_Category

Year,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Month,,,,,,,,,,
1,0.782609,0.837359,0.701288,0.590982,0.482287,0.484702,0.453301,0.323671,0.289050,0.262480
2,0.845411,0.731884,0.611916,0.569243,0.450081,0.461353,0.435588,0.246377,0.299517,0.210145
3,0.860709,1.000000,0.773752,0.476651,0.526570,0.505636,0.427536,0.321256,0.319646,0.253623
4,0.652979,0.876812,0.549919,0.444444,0.410628,0.468599,0.392110,0.246377,0.339775,0.260870
5,0.727858,0.759259,0.686795,0.454911,0.450081,0.495974,0.386473,0.238325,0.312399,0.255233
6,0.631240,0.644928,0.626409,0.504831,0.375201,0.421095,0.329308,0.238325,0.263285,0.158615
7,0.856683,0.646538,0.549114,0.424316,0.369565,0.459742,0.376006,0.235910,0.210145,0.193237
8,0.733494,0.987118,0.614332,0.400966,0.413849,0.448470,0.369565,0.301932,0.291465,0.216586
9,0.739130,0.915459,0.599034,0.487923,0.386473,0.441224,0.376812,0.296296,0.236715,0.181159
10,0.881643,0.738325,0.600644,0.387279,0.420290,0.458937,0.294686,0.315620,0.318035,0.202093
11,0.826087,0.725443,0.460548,0.390499,0.406602,0.391304,0.257649,0.367150,0.256844,0.192432
12,0.685990,0.614332,0.501610,0.344605,0.386473,0.334944,0.187601,0.245572,0.246377,0.242351

DayHour_Category = DayHour_Category / DayHour_Category.max()

In [15]:
source = ColumnDataSource(DayHour_Category)

In [29]:
Months = ['1','2','3','4','5','6','7','8','9','10','11','12']
Years = ['2008','2009','2010','2011','2012','2013','2014','2015','2016','2017']

In [30]:
p = figure(title='Annual Crimes per month',x_axis_label='Month',y_axis_label='Incidents', plot_width=1000, plot_height=700,x_range = FactorRange(factors=Months))

In [31]:
len(focuscrimes)
colorcrime = ['yellow','red','blue','green','purple','brown','#00ffff','#66ff66','#9933ff','#ff0080','#99ccff','#669900','#ff6600','#660033']

In [32]:
bar ={} # to store vbars
### here we will do a for loop:

items = [] ### for the custom legend // you need to figure out where to add it

for indx,i in enumerate(Years):
    bar[i] = p.vbar(x='Month',  top=i, source= DayHour_Category, 
                     fill_color=colorcrime[indx], line_color='black', fill_alpha=0.3,
                    ### we will create a vbar for each focuscrime
                      muted_alpha=0, muted = True) 
    items.append((i, [bar[i]])) ### figure where to add it
#i stands for a column that we use, top=y; we are specifying that our numbers comes from column i
#read up what legend_label, muted and muted_alpha do... you can add more attributes (you HAVE TO)

In [33]:
from bokeh.models import Legend

legend = Legend(items=items, location=(0, 400))

In [34]:


p.add_layout(legend, 'right')
p.legend.click_policy="mute" ### assigns the click policy (you can try to use ''hide'
output_file("narcotics.html")
show(p) #displays your plot